### ISSUE TITLE
The fdc3 open function throws the wrong error when the application is not found

### ISSUE THREAD

**Issue by ColinEberhardt** [InteropIO/finsemble-seed#772] opened 2022-08-25 22:10 UTC
When executing `window.fdc3.open("ThisAppDoesNotExist")`, an error should be thrown with the value `OpenError.AppNotFound`.

However, `OpenError.ErrorOnLaunch` is thrown instead.

**Comment by kriswest** [comment] 2022-08-26 09:54
Thanks Colin. Duplicate of #766 I think.

Do you know what version the test was run in? This should be fixed in Finsemble 7.3.0 I believe: https://documentation.finsemble.com/docs/welcome/changelog#730-

**Comment by kriswest** [comment] 2022-08-26 12:57
@mhmcclung when you're back from vacation could you look at this again? It is resolved for this case:
`let response = await fdc3.open({appId: "ThisAppDoesNotExist"})` - based on `appIdentifier`/`appId`
but not this case:
`let response = await fdc3.open("ThisAppDoesNotExist")` - deprecated version based on app `name`.

Probably just a case of swapping the error on this line: https://github.com/ChartIQ/finsemble-mono/blob/5abf1c1f6f5671a5bcbabe7718b9eb3b69f2a1b4/packages/core/src/platform/services/Interop/modules/resolver.ts#L2700

**Comment by kriswest** [comment] 2023-11-20 13:49
Also resolved a long time ago!

**Closed by kriswest** 2023-11-20 13:49 UTC
